model_name: "google/siglip-so400m-patch14-384"
data_compile_dir: "/kaggle/input/datasets/trnhngkhoashineekuwu/aic-compiled-data"
base_kf_dir: "/kaggle/input/datasets/nguynhuyds/aic-dataset"
device: "cuda"

visualization:
  top_n: 10
  max_length: 64
  vector_search_top_k: 200
  max_videos_per_query: 2
  use_objects: false
  object_weight: 0.15
  use_inverted: false
  use_transcripts: false
  transcript_weight: 0.35


