model_name: "google/siglip-so400m-patch14-384"
siglip_dir: "/kaggle/input/datasets/nguynhuyds/siglip-feature"
base_kf_dir: "/kaggle/input/datasets/nguynhuyds/aic-dataset"
device: "cuda"

visualization:
  top_n: 6
  max_length: 64
  vector_search_top_k: 200
  max_videos_per_query: 2
